#
# Makefile for the Ingenic JZ4750D.
#

obj-y += prom.o
obj-y += irq.o
obj-y += time.o
obj-y += reset.o
obj-y += setup.o
obj-y += timer.o

# board specific support
obj-$(CONFIG_JZ4750D_RZX50)	+= board-rzx50.o

obj-y += dts/
